/**
 * Maps internal error types to safe generic messages
 * Never exposes DB structure, field names or stack traces
 * to the client in production
 */
const getSafeErrorMessage = (err) => {
  /** Mongoose duplicate key — e.g. duplicate email */
  if (err.code === 11000) {
    return "This resource already exists.";
  }

  /** Mongoose validation errors */
  if (err.name === "ValidationError") {
    return "Invalid data provided. Please check your input.";
  }

  /** Mongoose bad ObjectId */
  if (err.name === "CastError") {
    return "Resource not found.";
  }

  /** JWT errors */
  if (err.name === "JsonWebTokenError") {
    return "Authentication failed.";
  }

  if (err.name === "TokenExpiredError") {
    return "Session expired. Please login again.";
  }

  /**
   * If error has a custom statusCode we set ourselves
   * via createError() — it's safe to show that message
   * since WE wrote it, not Mongoose/MongoDB
   */
  if (err.statusCode && err.statusCode < 500) {
    return err.message;
  }

  /**
   * All 500s get a completely generic message in production
   * Never expose internal server errors to client
   */
  return "Something went wrong. Please try again.";
};

/**
 * Global error handling middleware
 * Must be registered LAST in Express middleware chain
 * Catches all errors passed via next(error)
 */
const errorHandler = (err, req, res, next) => {
  const statusCode = err.statusCode || 500;

  /**
   * Log full error details on server for debugging
   * This is ONLY visible in server logs, never sent to client
   */
  console.error(`[ERROR] ${err.message}`);
  if (process.env.NODE_ENV === "development") {
    console.error(err.stack);
  }

  /**
   * Send safe sanitized message to client
   * In development expose a bit more for easier debugging
   * In production always use generic safe messages
   */
  res.status(statusCode).json({
    message: getSafeErrorMessage(err),
    /**
     * Only in development — give developers the real error
     * This block is completely stripped in production
     */
    ...(process.env.NODE_ENV === "development" && {
      debug: {
        originalMessage: err.message,
        stack: err.stack,
      },
    }),
  });
};

/**
 * Helper to create structured errors with custom status codes
 * Messages passed here are SAFE to show to clients
 * since they are written by us, not generated by DB/libraries
 * @param {string} message - Safe user-facing error message
 * @param {number} statusCode - HTTP status code
 * @returns {Error}
 */
const createError = (message, statusCode) => {
  const error = new Error(message);
  error.statusCode = statusCode;
  return error;
};

module.exports = { errorHandler, createError };
